### PR TITLE
Upgrade to use Nan>=2.0

### PR DESCRIPTION
**Pull request by chaosgame**
Hello @nicks, @dpup, @sboora, @dudeche, 

Please review the following commits I made in branch 'nathan-Nan'.

2315486cc0baeddb37e20094015e77c83ed75803 (2015-08-25 15:23:44 -0700)
Upgrade to use Nan>=2.0

R=@nicks
R=@dpup
R=@sboora
R=@dudeche

Test plan: 'not tested'

### CODE REVIEW

**Comment by dudeche** [comment]
Does this mean it won't work with nan <2.x?

**Comment by nicks** [comment]
can you also remove node 0.8 from travis while you're here?

**Comment by chaosgame** [comment]
@dudeche yeah, but Nan 2.x should still work with previous versions of Node.

**Comment by nicks** [comment]
lgtm

**Pull request merged**
